language: go

go:
  - 1.14.x

env:
  - GOSUMDB=off

script:
  - cd transports
  #- cd transports/Dust/v3; go test -v
  #- cd transports/meeklite/v3; go test -v
  #- cd transports/meekserver/v3; go test -v
  - cd obfs2/v3; go test -v
  - cd ../../obfs4/v3; go test -v
  - cd ../../Optimizer/v3; go test -v
  - cd ../../Replicant/v3; go test -v
  - cd ../../shadow/v3; go test -v

